[build]
command = "npm run build"
root = "src"
# Especifica la salida de la compilación Vite
output = "dist"

[deploy]
startCommand = "dist/assets/index-*.js"
# Define el comando para iniciar tu aplicación Vite
# Configura un redireccionamiento global para aplicaciones Vite
