[build]
command = "npm run build"
root = "src"
# Especifica la salida de la compilación Vite
output = "dist"

[deploy]
# Define el comando para iniciar tu aplicación Vite
startCommand = "http-server"  # Actualizado para el archivo server.js
# Configura un redireccionamiento global para aplicaciones Vite
[[redirects]]
from = "/*"
to = "/index.html"
status = 200