

[build]
  command = "npm run build"
  
  # Especificar el directorio de construcción
  output = "dist"

[deploy]
startCommand = "echo starting"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200